export const W_Experience = [
  {
    jobTitle: "Front End Developer",
    company: "Cheegle",
    description: "",
    startDate: "2019",
    endDate: "2020",
    location: "Fars ,Shiraz ,Iran",
    type: "Full Time",
    tools: ["Javascript", "React", "Redux", "Html", "Css", "Bootstrap"],
  },
  {
    jobTitle: "Front End JavaScript Developer ",
    company: "Donyaro",
    description: "",
    startDate: "2020",
    endDate: "2021",
    location: "Tehran ,Tehran ,Iran",
    type: "Full Time",
    tools: [
      "Javascript",
      "Typescript",
      "React",
      "Redux",
      "Html",
      "Css",
      "Bootstrap",
      "Webpack",
    ],
  },
  {
    jobTitle: "Full Stack Developer (MERN) ( Remote )",
    company: "Donyaro",
    description: "",
    startDate: "2021",
    endDate: "2022",
    location: "Tehran ,Tehran ,Iran",
    type: "Remote",
    tools: [
      "Javascript",
      "Typescript",
      "Nodejs",
      "Express",
      "MongoDB",
      "Postgresql",
      "ReactNative",
      "React",
      "Redux",
      "Mocha",
      "Chai",
      "Html",
      "Css",
      "Bootstrap",
    ],
  },

  {
    jobTitle: "Front End Assistant",
    company: "PARSA TECHNOLOGIES LIMITED",
    description: "",
    startDate: "2022",
    endDate: "2023",
    location: "Kabul ,Kabul ,Afghanistan",
    tools: [
      "Javascript",
      "Typescript",
      "React",
      "Redux",
      "Html",
      "Css",
      "Bootstrap",
      "Primereact",
      "Prmeface",
    ],
  },
  {
    jobTitle: "Senior Front End Developer",
    company: "PARSA TECHNOLOGIES LIMITED",
    description: "",
    startDate: "2023",
    endDate: "Current",
    location: "Kabul ,Kabul ,Afghanistan",
    tools: [
      "Javascript",
      "Typescript",
      "React",
      "ReactNative",
      "Redux",
      "Html",
      "Css",
      "Bootstrap",
    ],
  },
];
export const P_Info = {
  F_Name: "Morteza",
  L_Name: "Ahmadi",
  Bio: "Born 1993/03/21 in iran with afghan originality and living in Kabul , Afghanistan for now with my family and always eager to Read, Learn, share knowledge, and also love teamwork spirit",
  ima: "morteza1.jpg",
};
export const Con_Info = {
  mobile: ["+93744137683", "+93767196634"],
  email: "mortezaahmadi.af@gmail.com",
  location: "Afghanistan",
};
export const Edu_Info = {
  field: "Software Enginner",
  degree: "Bachelor",
  university: "Islamic Azad University of Shiraz",
  certificateImage: "",
  description: "",
  startDate: "2015",
  endDate: "2019",
  grad: "15.07 From 20",
};
export const LINKS = {
  git: "github.com/mortezaahmadiaf",
  linkedin: "https://www.linkedin.com/in/mortezaahmadi1638081a9",
};
